model-name: "testing_inf"
data:
  img_dir: "/mnt/efs/aimbl_2025/student_data/S-CG/Raw_tifs/ZSeries-08122025-1343_39893_y_ctx_3-000"
  file_format: "tiff_chunks" #['.tiff']['.zarr'][]
  norm_strategy: "percentile_per_img" #["stdev", "minmax", "percentile"]
  batch: 16 #int 
model:
  fmaps: 32
  kernel_size: 3
  n_depth: 4
  is_3d: False #defaults to False
checkpoint:
  ckp_dir: "/home/S-CG/noise2brian/checkpoints/testing_res/version_0/model.pt"
save:
  root_dir: "/mnt/efs/aimbl_2025/student_data/S-CG/Inf/Inf-test-1"
