model-name: "testing_inf"
data:
  img_dir: "/mnt/efs/aimbl_2025/student_data/S-CG/Avg_Proj/ZSeries-08122025-1505_39891_y_ctx-000"
  file_format: "tif" #['.tiff']['.zarr']
  norm_strategy: "percentile_per_img" #["stdev", "minmax", "percentile"]
  crop_size: [256, 256] #only works for 2D data 
  batch: 8 #int 
model:
  fmaps: 32
  kernel_size: 3
  n_depth: 4
  is_3d: False #defaults to False
train:
  split: [0.9, 0.1]
  epochs: 300
  metric: "DICE" #DICE,BFBS
  lr: 3e-4 #learning rate Albert's magic number

